defmodule OpenSslTest do
  use ExUnit.Case

  alias EllipticCurve.{PrivateKey, PublicKey, Ecdsa, Signature}

  test "sign" do
    # Generated by: openssl ecparam -name secp256k1 -genkey -out privateKey.pem
    {:ok, privateKeyPem} = File.read("test/privateKey.pem")

    {:ok, privateKey} = PrivateKey.fromPem(privateKeyPem)
    publicKey = PrivateKey.getPublicKey(privateKey)

    {:ok, message} = File.read("test/message.txt")

    signature = Ecdsa.sign(message, privateKey)

    assert Ecdsa.verify?(message, signature, publicKey)
  end

  test "verify signature" do
    # openssl ec -in privateKey.pem -pubout -out publicKey.pem

    {:ok, publicKeyPem} = File.read("test/publicKey.pem")

    # openssl dgst -sha256 -sign privateKey.pem -out signature.binary message.txt
    {:ok, signatureDer} = File.read("test/signatureDer.txt")

    {:ok, message} = File.read("test/message.txt")

    {:ok, publicKey} = PublicKey.fromPem(publicKeyPem)

    {:ok, signature} = Signature.fromDer(signatureDer)

    assert Ecdsa.verify?(message, signature, publicKey)
  end
end
