defmodule OpenSslTest do
  use ExUnit.Case

  alias EllipticCurve.{PrivateKey, Ecdsa}

  test "sign" do
    # Generated by: openssl ecparam -name secp256k1 -genkey -out privateKey.pem
    {:ok, privateKeyPem} = File.read("test/privateKey.pem")

    {:ok, privateKey} = PrivateKey.fromPem(privateKeyPem)
    publicKey = PrivateKey.getPublicKey(privateKey)

    {:ok, message} = File.read("test/message.txt")

    signature = Ecdsa.sign(message, privateKey)

    assert Ecdsa.verify?(message, signature, publicKey)
  end
end
